// <auto-generated />
using System;
using GA.UniCard.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GA.UniCard.Domain.Migrations
{
    [DbContext(typeof(UniCardDbContext))]
    [Migration("20240705192847_MigrateNowV15")]
    partial class MigrateNowV15
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GA.UniCard.Domain.Entitites.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Ordering_Date");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total_Amount");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsDescending();

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            OrderDate = new DateTime(2024, 4, 2, 23, 28, 47, 468, DateTimeKind.Local).AddTicks(7227),
                            TotalAmount = 492m,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            OrderDate = new DateTime(2024, 6, 15, 23, 28, 47, 468, DateTimeKind.Local).AddTicks(7249),
                            TotalAmount = 418m,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            OrderDate = new DateTime(2024, 5, 9, 23, 28, 47, 468, DateTimeKind.Local).AddTicks(7251),
                            TotalAmount = 290m,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            OrderDate = new DateTime(2024, 4, 16, 23, 28, 47, 468, DateTimeKind.Local).AddTicks(7253),
                            TotalAmount = 112m,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            OrderDate = new DateTime(2024, 5, 14, 23, 28, 47, 468, DateTimeKind.Local).AddTicks(7254),
                            TotalAmount = 501m,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            OrderDate = new DateTime(2024, 6, 14, 23, 28, 47, 468, DateTimeKind.Local).AddTicks(7256),
                            TotalAmount = 482m,
                            UserId = 6L
                        });
                });

            modelBuilder.Entity("GA.UniCard.Domain.Entitites.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Item_Price");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Item_Quantity");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsDescending();

                    b.HasIndex("ProductId")
                        .IsDescending();

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            OrderId = 1L,
                            Price = 36m,
                            ProductId = 1L,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 2L,
                            OrderId = 2L,
                            Price = 80m,
                            ProductId = 2L,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 3L,
                            OrderId = 3L,
                            Price = 75m,
                            ProductId = 3L,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4L,
                            OrderId = 4L,
                            Price = 62m,
                            ProductId = 4L,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 5L,
                            OrderId = 5L,
                            Price = 21m,
                            ProductId = 5L,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 6L,
                            OrderId = 3L,
                            Price = 21m,
                            ProductId = 2L,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 7L,
                            OrderId = 6L,
                            Price = 53m,
                            ProductId = 4L,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("GA.UniCard.Domain.Entitites.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Product_Description");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Product_Price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Product_Name");

                    b.HasKey("Id");

                    b.HasIndex("ProductName")
                        .IsDescending();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "THe milk is  good produce in mountins",
                            Price = 80m,
                            ProductName = "Milk"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "The Apple is  good produce in mountins",
                            Price = 26m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "THe Banana is  good produce in mountins",
                            Price = 83m,
                            ProductName = "Banana"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "THe Bread is  good produce in mountins",
                            Price = 12m,
                            ProductName = "Bread"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "THe Gold is  good produce in mountins",
                            Price = 54m,
                            ProductName = "Gold"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "THe Fish is  good produce in mountins",
                            Price = 89m,
                            ProductName = "Fish"
                        },
                        new
                        {
                            Id = 7L,
                            Description = "THe Beans is  good produce in mountins",
                            Price = 63m,
                            ProductName = "Beans"
                        },
                        new
                        {
                            Id = 8L,
                            Description = "THe Suggar is  good produce in mountins",
                            Price = 46m,
                            ProductName = "Suggar"
                        });
                });

            modelBuilder.Entity("GA.UniCard.Domain.Entitites.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User_Name");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "Aapkhazava22@gmail.com",
                            Password = "Guga123",
                            UserName = "Guga123#"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "Guga342@gmail.com",
                            Password = "Gaga1234",
                            UserName = "Guga13guga##"
                        },
                        new
                        {
                            Id = 3L,
                            Email = "Aapkhazava22@gmail.com",
                            Password = "Giga12346$",
                            UserName = "Guga123#"
                        },
                        new
                        {
                            Id = 4L,
                            Email = "NikaArtmeladze@gmail.com",
                            Password = "Guga%34",
                            UserName = "Guga123#"
                        },
                        new
                        {
                            Id = 5L,
                            Email = "Giorgi123@gmail.com",
                            Password = "Giorgi324",
                            UserName = "Guga123#"
                        },
                        new
                        {
                            Id = 6L,
                            Email = "UniPayAdmin@gmail.com",
                            Password = "Admin",
                            UserName = "Admin#"
                        },
                        new
                        {
                            Id = 7L,
                            Email = "Aapkhazava2200@gmail.com",
                            Password = "User4562",
                            UserName = "User#"
                        });
                });

            modelBuilder.Entity("GA.UniCard.Domain.Entitites.Order", b =>
                {
                    b.HasOne("GA.UniCard.Domain.Entitites.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GA.UniCard.Domain.Entitites.OrderItem", b =>
                {
                    b.HasOne("GA.UniCard.Domain.Entitites.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GA.UniCard.Domain.Entitites.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GA.UniCard.Domain.Entitites.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("GA.UniCard.Domain.Entitites.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("GA.UniCard.Domain.Entitites.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
